### ISSUE TITLE
TypeError: Cannot destructure property 'content' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by FunkiCraft** [Nuggies-bot/dropdown-roles-example#1]
I become this Error when the Bot trys to create the Dropdown Roles after i sending done:

```
static async create(client, { content, role, channelID, type, min, max }) {
                              ^

TypeError: Cannot destructure property 'content' of 'undefined' as it is undefined.
```

**Comment by LegItMate** [comment]
The methods were changed in recent versions, you may want to check out [beta docs](https://nuggies-docs-beta.netlify.app/#example) which has examples on how to use the methods.

If you don't wish to go there, then check the code in one of the branches [here](https://github.com/Nuggies-bot/dropdown-roles-example/blob/slash-commands-v13/commands/createdp.js#L47).

**Comment by Assassin-1234** [comment]
replacing 
```js
Nuggies.dropdownroles.create({message, ...})
```
with
```js
Nuggies.dropdownroles.create(client, {content...})
```
should fix this
