### ISSUE TITLE
very sussy amogus baka

### ISSUE THREAD

**Issue by face-hh** [Nuggies-bot/dropdown-roles-example#3]
baka sussy amogus very owo

**OwO**

```
 ____ ___          ____ ___ 
|    |   \__  _  _|    |   \
|    |   /\ \/ \/ /    |   /
|    |  /  \     /|    |  / 
|______/    \/\_/ |______/  
                            ```

**Comment by face-hh** [comment]
i sleep with a gun

**Comment by face-hh** [comment]
OwOOwOOwOOwO                                                                                        OwOOwOOwOOwO
OwO                    OwO           OwO                                        OwO                 OwO                    OwO
OwO                    OwO            OwO          OwOOwO        OwO                  OwO                    OwO
OwO                    OwO             OwO       OwO   OwO      OwO                   OwO                    OwO
OwO                    OwO              OwO     OwO     OwO    OwO                    OwO                    OwO
OwO                    OwO               OwO   OwO       OwO  OwO                     OwO                    OwO
OwOOwOOwOOwO                 OwOOwO         OwOOwO                      OwOOwOOwOOwO

**Comment by face-hh** [comment]
```OwOOwOOwOOwO                                                                                        OwOOwOOwOOwO
OwO                    OwO           OwO                                        OwO                 OwO                    OwO
OwO                    OwO            OwO          OwOOwO        OwO                  OwO                    OwO
OwO                    OwO             OwO       OwO   OwO      OwO                   OwO                    OwO
OwO                    OwO              OwO     OwO     OwO    OwO                    OwO                    OwO
OwO                    OwO               OwO   OwO       OwO  OwO                     OwO                    OwO
OwOOwOOwOOwO                 OwOOwO         OwOOwO                      OwOOwOOwOOwO

**Comment by face-hh** [comment]
LET OWO DOMINATE

**Comment by face-hh** [comment]
![image](https://user-images.githubusercontent.com/69168154/156882535-6a1cde9a-9e93-42ad-ba62-b8e377f930d8.png)

**Comment by Assassin-1234** [comment]
convo locked

eat toes
